README.md, notify-if-background
When wmctrl is installed, the terminal window always steals focus, it is very distracting.
I think this feature should be only explicitly enabled. Instead by default we can use attention demand. This means that the window icon on the task bar will blink.
=> Use attention demand instead of focus stealing for terminal window by default (Linux)

notify-if-background
This commit fixes terminal-notifier options.
Do not focus the terminal when click the notification.
Focus the terminal when click the notification.
Thanks to great project.
=> Fixes terminal-notifier options

README.md, notify-if-background
I want to receive notification with sound, so I create this PR.
This commit is enable to play sound for notification.
It currently works on mac only, because it is using terminal-notifier command line option.
=> Enable to play sound (on mac)

README.md, notify-if-background
Allow to use "error-icon" and "success-icon" settings on Linux, currently they work only on Mac OS.
=> Icons support for Linux

README.md, notify-if-background
It doesn't work correctly for terminals running in daemon mode (like [urxvt](https://linux.die.net/man/1/urxvtd)).
=> Add option to disable urgency hint with wmctrl

notify.plugin.zsh, tests/xdotool.zunit, xdotool/functions
- `zstyle -b` apparently returns false if the boolean value is false, so
we need to append `|| true` to it.
- use windowunmap instead of windowminimize, which should work tiling
window managers
- get rid of `sleep` and use `--sync` arg to verify xdotool finished
=> Fix tests on linux:

notify.plugin.zsh
Hello. I wanted to ask this first, but I was not able to create an issue, so I ventured forward, straight to a pull request :smiley: 
I'm not sure if you meant it, but here
https://github.com/marzocchi/zsh-notify/blob/master/notify.plugin.zsh#L12
You explicitly redirect an error message to stdout. Not only it looks weird and redundant, but it breaks one of my dotfiles :stuck_out_tongue:
=> Redirecting foreground-detection error message to stderr

xdotool/functions
`xdsotool getactivewindow` returns an error if no window is currently active:
```
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
```
The docs mention that it getactivewindow "is often more reliable than getwindowfocus", but I have had no problems with getwindowfocus.
Alternatively, find another way of suppressing the error and treating it like the terminal has lost focus?
=> Use xdsotool getwindowfocus

README.md, notify.plugin.zsh, xdotool/functions
It is better then `notify-send` as application name.
=> Add application and expire time to notify-send

README.md
iterm-notify is archived, so it doesn't seem like good advice to refer people to it, especially since this project works fine for iTerm2.
=> remove reference to archived project

applescript/functions, notify.plugin.zsh, tests/iterm2.zunit, tests/zsh-notify.zunit
tmux 3.2 has started to set `TERM_PROGRAM` to `tmux`. See [changes from 3.1c to 3.2](https://github.com/tmux/tmux/blob/master/CHANGES)
This causes zsh-notify to stop working on macOS because it assumes `TERM_PROGRAM` to be set to `iTerm2.app` or `Apple_Terminal`.
For me, zsh-notify fails silently, but I think that depends on how you load zsh-notify. You may get the error message `zsh-notify: unsupported environment`
So, we should make zsh-notify smarter in how it detects iTerm2.
Unfortunately, it isn't completely trivial to do that.
The official way to detect iTerm is apparently this rather long script https://iterm2.com/utilities/it2check
In this PR I suggest a simplistic method of checking `ITERM_SESSION_ID`. That seems to be set even inside tmux, as long as the tmux session was started …
=> Fix "unsupported environment" fail on tmux 3.2 for iTerm2 and Apple Terminal

xdotool/functions
To prevent saving command to history, user may use a space before command. For notify-send this results in an error.
To properly fix this, more sophisticated app name detection (line 68) required.
=> Fix "Invalid number of options" error when command starts with a space

applescript/resources/is-iterm2-active.applescript
Old way of checking if terminal window is active didn't work for hotkey
window with `Floating window` option active. Used iTerm scripting API
to use different checks, if last used window is the hotkey window.
=> Add check for active hotkey window in iTerm2

notify.plugin.zsh
=> FIX always-notify-on-failure

README.md, notify.plugin.zsh, xdotool/functions
This add support for disabling check on focus.
This is useful, at least for me: the fact that the window has focus does not imply at all that I am looking at it. I could be AFK.
Also, this allows Wayland users to use this plugin (of course with not as many functionalities as they could on X, but still)
=> Check focus

xdotool/functions
Currently focus checking on linux has the following problems:
1. It ignores the default value of zstyle setting, because its value is [checked](https://github.com/marzocchi/zsh-notify/blob/9517abdbac9977700a24aa22d8ccc830b985d125/xdotool/functions#L140) before it is set [here](https://github.com/marzocchi/zsh-notify/blob/9517abdbac9977700a24aa22d8ccc830b985d125/notify.plugin.zsh#L30).
2. It does not allow you to set zstyle setting after the plugin is already loaded, because it only checks for it during the loading (while the rest of the settings _must_ be set after that).
This PR fixes the problems described above.
=> Fix focus checking on Linux

README.md
The linux part of the requirements was missing xdotool and wmctrl. The absence of the latter resulted on my machine in an error message 'unknown environment'.
Adding those two to the requirements should make the onboarding smoother.
=> Add more requirements to Readme

notify.plugin.zsh
Previously, the two global variables used to store state during command execution were named `last_command` and `start_time`. Since those are both variable names that could easily be used in a shell session or a function, this adds a `zsh_notify_` prefix to avoid potential conflicts.
=> Add zsh_notify_ prefix to global variables

notify.plugin.zsh
This switches to getting the current time from the shell variable `$EPOCHSECONDS` rather than executing the `date` command. This results in the average time of the combined before and after functions going from 10ms to 6ms on my machine.
The `$EPOCHSECONDS` variable was added to the Zsh codebase on 2003-10-08 and appears to have been released in Zsh 4.2.0 on 2004-03-19 (verified by looking at the Zsh 4.2.0 release tarball).
---
I suspect this won’t make a difference in the vast majority of situations, but it seemed cleaner and more reliable to me so I figured I’d propose it and see what you thought.
=> Use $EPOCHSECONDS instead of $(date)

xdotool/functions
This pull request allows the notification sound to play in the background. With this change, you can start typing the next command without waiting for the sound to finish playing.
The code for playing the sound has been updated to include the &> /dev/null & redirection, which runs the command in the background and discards both standard output and standard error.
=> Play notification sound in background on Linux
